### ISSUE TITLE
能否增加拉取git项目

### ISSUE THREAD

**Issue by dcsunny** [mgr9525/gokins#18]
体验了一下，整体效果还不错，不过我要用于部署项目的话，需要做以下几件事:
1.拉取git项目
2. 编译项目
3.将编译后的包发布到线上环境

这方面使用上挺不方便的，希望能做的比jenkins更加方便一些。 如果全部都要自己写shell脚本还挺麻烦的- -

**Comment by jimbirthday** [comment]
你好。感谢你的支持。
但是有几点需要和你确认一下，请问下你体验的版本是哪一个版本呢。
如果是v0.2.0版本已经增加了github、gitlab、gitee的webhook功能。
你指的编译项目指的具体是什么呢？
我们目前正在做插件功能，应该能满足你上诉的要求

**Comment by dcsunny** [comment]
我是master拉取下来，执行build的。   不是webhook功能，我只说webhook后，在流水线那里。按照您现在的逻辑，是我需要写一个逻辑去git clone或者git pull项目，在拉取中，需要用到ssh key吧，ssh key在哪里管理呢，这些目前还没有支持。。。
至于编译的话，这个jenkins现在也是自己写脚本，重点是第一步拉取项目这个还不太方便呢。

**Comment by dcsunny** [comment]
jenkins目前的做法是，设置git地址，设置ssh key， 设置拉取的项目使用的目录就可以了，还挺方便的。 

还有一个建议哈，就是我觉得您这个项目与触发器有点割裂，触发器属于某个项目里的，可以放到项目内，这个配置和使用比较清楚触发器属于哪个项目的，或者说项目下设置了哪些触发器

**Comment by mgr9525** [comment]
谢谢你的建议，代码管理我们提前纳入规划，触发器这块可以在流水线里加上绑定信息，应该能满足你的这个需求

**Comment by mgr9525** [comment]
[demo](http://gokins.cn:8030/)
