### ISSUE TITLE
通过dockerfile构建的容器，执行命令问题

### ISSUE THREAD

**Issue by a5635268** [mgr9525/gokins#21]
执行的shell环境其实是容器环境，不知道怎么破？ 求教

**Comment by mgr9525** [comment]
能说详细一点吗？你是怎么运行gokins的呢？

**Comment by a5635268** [comment]
docker build -t gokins:v1 .
docker run gokins:v1 -d -p 8030:8030 -name gokins

然后进应用，环境变量检测。 检测结果都是容器内的环境。

**Comment by mgr9525** [comment]
那你用容器跑的进程，肯定是容器的环境，想要主机的环境，就下载可执行文件执行就行了

**Comment by jimbirthday** [comment]
目前gokins的docker镜像并没有和宿主机做通信。你描述的应该是类似jekins的docker部署之后能和宿主机做通信吧

**Comment by a5635268** [comment]
> 
> 
> 目前gokins的docker镜像并没有和宿主机做通信。你描述的应该是类似jekins的docker部署之后能和宿主机做通信吧

嗯嗯，就是这个意思，想搞到docker-compose里面做一键启动

**Comment by jimbirthday** [comment]
额，目前还不能这样操作。不过这部分我们也会考虑的。您现在可以先使用可执行文件的方式来使用gokins，感谢你的支持！
