### ISSUE TITLE
实践的时候遇到了一些问题

### ISSUE THREAD

**Issue by Uchiha-Peng** [mgr9525/gokins#28]
#### 首先，项目的Dockerfile是有一些问题的，我用的修正如下
```
FROM golang:1.15.2-alpine AS builder
WORKDIR /build
RUN apk add git gcc libc-dev \
    && git clone https://github.com/mgr9525/gokins.git /build
RUN GOOS=linux GOARCH=amd64 go build -o bin/gokins main.go
FROM alpine:latest AS final
RUN apk update \
    && apk upgrade \
    && apk --no-cache add openssl \
    && apk --no-cache add ca-certificates \
    && rm -rf /var/cache/apk \
    && mkdir -p /app
COPY --from=builder /build/bin/gokins /app
WORKDIR /programs
EXPOSE 8030
ENTRYPOINT ["/app/gokins"]

1.应先执行 WORKDIR /build 命令创建/build目录，再执行git clone将代码clone到/build目录下，原有的Dockerfile打包镜像会出现找不到/build目录的问题

2.mkdir -p /app已经创建了，就无需再 WORKDIR /app，而且这个目录也无需挂在到宿主机

3.EXPOSE 8030 暴露8030端口看似多此一举，但是至少可以让打包镜像的人了解程序到底运行在哪个端口，免得还要先跑一个容器用natstat命令去查看。。。。。。 
```
#### 运行容器命令如下
```
docker run -d -p 8030:8030 -v /programs:/programs --restart=always --name gokins susanoo/gokins:1.0
```
#### 遇到的问题：

1. 居然要手动git clone仓库到本地。。。。那从何体现gokins作为CICD工具的可用性？
2. 容器运行后，并没有像一些博客里提到的有插件列表这个功能。。。。。。

#### 最后

1. 作者要做开源就好好做，做个真正可用、好用的工具吧，谢谢。

**Comment by jimbirthday** [comment]
目前我们正在准备1.0的版本。您上述问题中的部分也在我们的规划中，目前暂未放出一个时间节点，但是估计在三月左右，我们将会发布公告，感谢你的关注和建议。

**Comment by Uchiha-Peng** [comment]
能不能给个可用的版本先试试，需不需要手动git clone都无所谓了。

**Comment by Uchiha-Peng** [comment]
![image](https://user-images.githubusercontent.com/20633089/104164210-8fa53900-5432-11eb-816f-a4c4fe368b13.png)

![image](https://user-images.githubusercontent.com/20633089/104164446-e1e65a00-5432-11eb-934e-1b121a819715.png)

![image](https://user-images.githubusercontent.com/20633089/104164752-5caf7500-5433-11eb-8af4-0d9b063c3511.png)

如何能显示——插件列表

**Comment by jimbirthday** [comment]
目前master分支上就是可用的版本，你可以clone代码编译，也可以直接下载Releases。目前插件对应的是每条流水线内部的插件，所以需要点进去看。你可以看下read.me 。也可以到http://gokins.cn:8030 这个地址先去体验一下。里面有几个demo应该能够帮到你。

关于插件。你需要新增一个，才能看到
![image](https://user-images.githubusercontent.com/38313933/104164837-7f418e00-5433-11eb-81db-fccf4414e2fd.png)
