### ISSUE TITLE
请问，这项目还有人维护吗？怎么看上去好几个月没更新了似的。

### ISSUE THREAD

**Issue by wildfire810** [mgr9525/gokins#37]
也没有其他动静啊。网站倒是还在。

**Comment by mgr9525** [comment]
你好@wildfire810
这个项目转移到  https://github.com/gokins/gokins  维护了

**Comment by wildfire810** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linsk ***@***.***&gt;; 
发送时间: 2022年8月12日(星期五) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mgr9525/gokins] 请问，这项目还有人维护吗？怎么看上去好几个月没更新了似的。 (Issue #37)





 
这个项目转移到https://github.com/gokins/gokins维护了
